![三层神经网络](..\image\2.png)

In [1]:
# 对于上面的神经网络用代码实现
import numpy as np
X = np.array([1.0,0.5])
W1 = np.array([[0.1,0.3,0.5],[0.2,0.4,0.6]])
B1 = np.array([0.1,0.2,0.3])
A1 = np.dot(X,W1)+B1
print(A1)

[0.3 0.7 1.1]


In [2]:
# 神经源中在重新设置激活函数
# 如下图所示

![三层神经网络](..\image\3.png)

In [3]:
# 使用sigmoid激活函数
# sigmoid函数实现
def sigmoid(x):
    return 1/(1+np.exp(-x))
Z1 = sigmoid(A1)
print(A1)
print(Z1)

[0.3 0.7 1.1]
[0.57444252 0.66818777 0.75026011]


In [4]:
# 接下来实现第一层到第二层的信号传递

![三层神经网络](..\image\4.png)

In [5]:
w2 = np.array([[0.1,0.4],[0.2,0.5],[0.3,0.6]])
b2 = np.array([0.1,0.2])
A2 = np.dot(Z1,w2) + b2
Z2 = sigmoid(A2)
print(Z2)

[0.62624937 0.7710107 ]


In [6]:
# 最后是第三层到输出层的信号传递
# 但是最后一层激活函数和前面不同，按原样输出即可
def identity_function(x):
    return x
W3 = np.array([[0.1,0.3],[0.2,0.4]])
B3 = np.array([0.1,0.2])

A3 = np.dot(Z2,W3) + B3
Y = identity_function(A3)
print(Y)

[0.31682708 0.69627909]


In [7]:
# 输出层的激活函数不同于隐藏层的激活函数


In [10]:
# 代码实现小结

# 初始化权重
def init_network():
    network = {}
    network['W1'] = np.array([[0.1, 0.3, 0.5],
                              [0.2, 0.4, 0.6]])
    network['b1'] = np.array([0.1, 0.2, 0.3])
    network['W2'] = np.array([[0.1, 0.4],
                              [0.2, 0.5],
                              [0.3, 0.6]])
    network['b2'] = np.array([0.1, 0.2])
    network['W3'] = np.array([[0.1, 0.3],
                              [0.2, 0.4]])
    network['b3'] = np.array([0.1, 0.2])
    return network

# 神经网络工作
def forward(network,x):
    w1,w2,w3 = network['W1'],network['W2'],network['W3']
    b1,b2,b3 = network['b1'],network['b2'],network['b3']

    a1 = np.dot(x,w1) + b1
    z1 = sigmoid(a1)
    a2 = np.dot(z1,w2) + b2
    z2 = sigmoid(a2)
    a3 = np.dot(z2,w3) + b3
    y = identity_function(a3)

    return y
network = init_network()
x = np.array([1.0,0.5])
y = forward(network,x)
print(y)

[0.31682708 0.69627909]
